package com.xm6680.it.cavestalker;

public enum CaveStalkerPhase {
    WARNING,
    CHASING,
    BLOCKED_VANISH,
    RECEIVER_VIBRATION_WARNING,
    WAITING_FOR_RECEIVER_OPEN,
    RECEIVER_TRAP_MESSAGE,
    WAITING_FOR_LOOK_BACK,
    LOOK_BACK_EMPTY,
    SPAWNED_BEHIND,
    WAITING_FOR_PLAYER_TURN_BACK,
    FACE_SCARE,
    EASTER_EGG_END,
    CAUGHT,
    ESCAPED,
    END
}
